[2023-09-12 16:32:51,585] INFO _log() L224  127.0.0.1 - - [12/Sep/2023 16:32:51] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-12 16:32:51,773] INFO _log() L224  127.0.0.1 - - [12/Sep/2023 16:32:51] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-12 16:32:51,855] INFO _log() L224  127.0.0.1 - - [12/Sep/2023 16:32:51] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-12 16:32:52,144] INFO _log() L224  127.0.0.1 - - [12/Sep/2023 16:32:52] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-12 16:32:52,308] INFO _log() L224  127.0.0.1 - - [12/Sep/2023 16:32:52] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-12 16:32:59,448] ERROR log_exception() L1449 Exception on /editar/ [PUT] - call_trace=C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\app.py", line 78, in editar
    produto = session.query(Produto).filter(Produto.id == body.id).first()
                                                          ^^^^^^^
AttributeError: 'ProdutoEditarSchema' object has no attribute 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\flask_openapi3\scaffold.py", line 273, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\app.py", line 97, in editar
    logger.error(f"Erro ao editar produto com ID {produto_id}: {str(e)}")
                                                  ^^^^^^^^^^
NameError: name 'produto_id' is not defined
[2023-09-12 16:32:59,464] INFO _log() L224  127.0.0.1 - - [12/Sep/2023 16:32:59] "[35m[1mPUT /editar/ HTTP/1.1[0m" 500 - - call_trace=C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-12 16:33:44,967] INFO _log() L224  127.0.0.1 - - [12/Sep/2023 16:33:44] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-12 16:33:44,999] INFO _log() L224  127.0.0.1 - - [12/Sep/2023 16:33:44] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-12 16:33:45,017] INFO _log() L224  127.0.0.1 - - [12/Sep/2023 16:33:45] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-12 16:33:45,062] INFO _log() L224  127.0.0.1 - - [12/Sep/2023 16:33:45] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-12 16:33:45,385] INFO _log() L224  127.0.0.1 - - [12/Sep/2023 16:33:45] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-12 16:33:45,423] INFO _log() L224  127.0.0.1 - - [12/Sep/2023 16:33:45] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-12 16:33:52,534] ERROR log_exception() L1449 Exception on /editar/ [PUT] - call_trace=C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\app.py", line 78, in editar
    produto = session.query(Produto).filter(Produto.id == body.id).first()
                                                          ^^^^^^^
AttributeError: 'ProdutoEditarSchema' object has no attribute 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\flask_openapi3\scaffold.py", line 273, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\app.py", line 97, in editar
    logger.error(f"Erro ao editar produto com ID {produto_id}: {str(e)}")
                                                  ^^^^^^^^^^
NameError: name 'produto_id' is not defined
[2023-09-12 16:33:52,627] INFO _log() L224  127.0.0.1 - - [12/Sep/2023 16:33:52] "[35m[1mPUT /editar/ HTTP/1.1[0m" 500 - - call_trace=C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-12 16:34:12,883] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.179:5000 (Press CTRL+C to quit) - call_trace=C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-12 16:34:17,208] INFO _log() L224  127.0.0.1 - - [12/Sep/2023 16:34:17] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-12 16:34:17,331] INFO _log() L224  127.0.0.1 - - [12/Sep/2023 16:34:17] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-12 16:34:17,977] INFO _log() L224  127.0.0.1 - - [12/Sep/2023 16:34:17] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-12 16:34:17,997] INFO _log() L224  127.0.0.1 - - [12/Sep/2023 16:34:17] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-12 16:34:18,028] INFO _log() L224  127.0.0.1 - - [12/Sep/2023 16:34:18] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\aluga.com\Desktop\TADEU MONTE\Projeto-MVP\env\Lib\site-packages\werkzeug\_internal.py L224 
